
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/deal
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    properties:
      hibernate:
        show_sql: true
    database: mysql

server:
  port: 8001
